services:

  apache:
    image: custom-apache
    container_name: apache
    build:
      context: ./requirements/apache
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nginx
    networks:
      - ft_transcendence
    volumes:
      - vault-certs:/etc/apache2/ssl
    # secrets:
    #   - ssl_certificate
    #   - ssl_certificate_key

  postgres:
    image: custom-postgresql
    container_name: postgres
    build:
      context: './requirements/postgresql'
      dockerfile: Dockerfile
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - ft_transcendence
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: custom-backend
    container_name: backend
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    networks:
      - ft_transcendence
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - vault_token:/vault/token/backend
      - ./requirements/backend/tools/entrypoint.sh:/usr/src/app/entrypoint.sh
    ports:
      - "8000:8000"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m
      timeout: 10s
      retries: 5

  frontend:
    image: custom-frontend
    container_name: frontend
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
    restart: "no"
    networks:
      - ft_transcendence
    volumes:
      - frontend_build:/usr/src/app/dist
    healthcheck:
      test: ["CMD", "test", "-f", "/usr/src/app/build/index.html"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  nginx:
    image: custom-nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - frontend_build:/usr/share/nginx/html
    networks:
      - ft_transcendence
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5

  vault:
    image: custom-vault
    container_name: vault
    build:
      context: ./requirements/vault
      dockerfile: Dockerfile
    restart: always
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_API_ADDR: "http://vault:8200"
    ports:
      - "8200:8200"
    volumes:
      - vault_build:/vault/data
    networks:
      vault_network:
          ipv4_address: 192.168.100.2
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  vault-init:
    image: vault-init
    container_name: vault-init
    build:
      context: ./requirements/vault-init
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - vault
    environment:
      VAULT_ADDR: "http://vault:8200"
    volumes:
        - ../secrets/unseal_keys:/vault-init/unseal
        - ../secrets/ssl:/vault-init/ssl 
        - vault_agent_auth:/vault/auth
    networks:
      vault_network:
          ipv4_address: 192.168.100.3


  vault-agent:
    image: custom-vault-agent
    container_name: vault-agent
    build:
      context: ./requirements/vault-agent
      dockerfile: Dockerfile
    restart: always
    cap_add:
      - IPC_LOCK
      - SETFCAP
    environment:
      VAULT_ADDR: "http://vault:8200"
    volumes:
      - ./requirements/vault-agent/conf/vault-agent.hcl:/vault/config/vault-agent.hcl
      - vault_agent_auth:/vault/auth
      - vault-certs:/vault/certs
    depends_on:
      - vault
    ports:
      - "8201:8201"
    networks:
      vault_network:
          ipv4_address: 192.168.100.4
      ft_transcendence: {}
    security_opt:
      - no-new-privileges:true

networks:
  vault_network:
    name: vault_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24

volumes:
  frontend_build:
  vault_build:
  vault_token:
  vault_logs:
  vault_files:
  vault-certs:
  vault_data:
  database-postgres:
  postgres_data:
  vault_agent_auth:

# secrets:
#   vault_unseal_keys:
#     file: ../secrets/unseal_keys.json
#   vault_secrets_json:
#     file: ../secrets/secrets.json
#   ssl_certificate:
#     file: ../secrets/ssl/certificate.crt
#   ssl_certificate_key:
#     file: ../secrets/ssl/certificate.key