GAME_STATE_UPDATE_INTERVAL = 0.0167  # 60 updates per second (1 / 60)
# GAME_STATE_UPDATE_INTERVAL = 0.034  # 30 updates per second (1 / 30)

PADDLE_DEFAULT_WIDTH = 2.5  # %
PADDLE_DEFAULT_HEIGHT = 13  # %
PADDLE_STRETCHING_FACTOR = 0.3
PADDLE_MAX_SPEED = 1.5
PADDLE_ACCELERATION = 0.1
PADDLE_DEACCELERATION = 0.1
PADDLE_BOUNDARY_GRACE_OFFSET = 1  # %

BALL_OFF_BOUNDS_OFFSET = 15  # %
BALL_DEFAULT_WIDTH = 2  # %
BALL_DEFAULT_HEIGHT = 16  # %
BALL_DEFAULT_POSITION_X = 50
BALL_DEFAULT_POSITION_Y = 50
BALL_MIN_VELOCITY_X = 0.8
BALL_MAX_VELOCITY_X = 4
BALL_VELOCITY_X_INCREMENT = 0.07
BALL_MIN_VELOCITY_Y = 0.05
BALL_MAX_VELOCITY_Y = 2
BALL_MAX_VELOCITY_CHANGE_ON_HIT = 0.2
MAX_CURVE_ANGLE = 0.4
BALL_DEFAULT_VELOCITY_Y_OPTIONS = [1, -1]
