GAME_STATE_UPDATE_INTERVAL = 0.0167  # 60 updates per second (1 / 60)

PADDLE_DEFAULT_WIDTH = 2  # %
PADDLE_DEFAULT_HEIGHT = 16  # %
PADDLE_MAX_SPEED = 1.5
PADDLE_ACCELERATION = 0.1
PADDLE_DEACCELERATION = 0.1

BALL_OFF_BOUNDS_OFFSET = 15  # %
BALL_DEFAULT_WIDTH = 2  # %
BALL_DEFAULT_HEIGHT = 16  # %
BALL_DEFAULT_POSITION_X = 50
BALL_DEFAULT_POSITION_Y = 50
BALL_MIN_VELOCITY_X = 0.8
BALL_MAX_VELOCITY_X = 4
BALL_MIN_VELOCITY_Y = 0.1
BALL_MAX_VELOCITY_Y = 2
BALL_DEFAULT_VELOCITY_Y_OPTIONS = [1, -1]
