# Generated by Django 5.1.4 on 2025-01-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_remove_user_id_alter_user_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='temp_id',
            new_name='id',
        ),
    ]
