# Generated by Django 5.1.4 on 2025-03-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="players",
            field=models.JSONField(default=list),
        ),
    ]
