# Generated by Django 5.1.4 on 2025-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_tournament_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("finished", "Finished"),
                    ("abandoned", "Abandoned"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
