# Generated by Django 5.1.4 on 2025-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_alter_tournament_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="game",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="tournament",
            name="gameplay",
            field=models.JSONField(default=dict),
        ),
    ]
