# Generated by Django 5.1.4 on 2025-04-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_tournament_game_tournament_gameplay"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
