# Generated by Django 5.1.4 on 2025-02-08 12:39

import project.apps.intrauth.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntraUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('intra_login', models.CharField(max_length=8, unique=True)),
                ('avatar', models.CharField(max_length=100)),
                ('wallet', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True)),
            ],
            managers=[
                ('objects', project.apps.intrauth.managers.IntraUserManager()),
            ],
        ),
    ]
