# Generated by Django 5.1.4 on 2025-02-11 21:50

import project.apps.intrauth.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntraUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('intra_login', models.CharField(max_length=8, unique=True)),
                ('avatar', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='intrauth_in_email_d6ff60_idx'), models.Index(fields=['intra_login'], name='intrauth_in_intra_l_0a6681_idx')],
            },
            managers=[
                ('objects', project.apps.intrauth.managers.IntraUserManager()),
            ],
        ),
    ]
