# Generated by Django 5.1.4 on 2025-02-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='intrauser',
            name='intrauth_in_email_d6ff60_idx',
        ),
        migrations.RemoveIndex(
            model_name='intrauser',
            name='intrauth_in_intra_l_0a6681_idx',
        ),
    ]
